language: node_js
node_js:
- 6
cache:
  directories:
  - node_modules
script:
- npm run build
- npm test
branches:
  only:
  - develop
deploy:
  provider: firebase
  token:
    secure: SG4hMV9mvhcMchYbw2qA0NkLmiV+itmfft+9IeUmdwu64wm1enc+hIgirYDciMXRwBqC13Wl2CdMAd9X9Cq+qyh2G9yxTtN2LAEAIsQJ2+EX6WLHvHEJfK7FtNX2KgT7MzG+5it7MnkNp5choPwQU3BS1e6Hcd2kHnqC4TZjGgQNnTSmtQeTRAAzkorSsvEpOpWZpy8BQYzT9jI4WKHMfNRCo4mI0mKCHjGAheyhO1eXhf9DMFZmWj99mxChHhnPt4glssA3cjvr1wtrJrALK/kX/lSbb3d87H9jsK9lMZiBl8exeiZgT+sGHJcQ7Aqj6xTMEb35EStFzcIX5IrwdNPmvx7UWAcsIBITsJ8WdcXrQ+0J3y6HJRu0KeoGNu+HFJT/6GEbsrH0h4ItHmYZF21ucSeavShLXf1croPFUaNbsMPrTwhxGrWoUVAMFatOLtS2cFpio4nOuJToQ8EZjn1MgDL1mGI9nHDQJvjd5tN9O97hUTmZ1k1Ti0/MZ7eBCkKNts+U+41X35um2gtYQ895I7dhvydweYBRX12v1gYwBclS9g8Ndr4Bl40usLT1XryFLoCC8+yaul45C2ik0C21qsSgcQEnZ3+++h3ir1ryMmTwI7fpRZP+4ei6uRlfUzCL3KwKDeASA63585+MWR0oNyHLps0AYl6sX+2Ufk8=
  on:
    branch: develop
  message: "Firebase Deploy"